// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARbx8YUUIfVtnBwHDL52jc1AHVCqbwq5c',
    appId: '1:234336593435:web:174411d370a90f9f087abe',
    messagingSenderId: '234336593435',
    projectId: 'wallet-hunter-f590f',
    authDomain: 'wallet-hunter-f590f.firebaseapp.com',
    storageBucket: 'wallet-hunter-f590f.firebasestorage.app',
    measurementId: 'G-38WVECRZ0S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbbgL17hE9ocSe_w2u8OaNoolhs5-vVFo',
    appId: '1:234336593435:android:6f7866501d968a61087abe',
    messagingSenderId: '234336593435',
    projectId: 'wallet-hunter-f590f',
    storageBucket: 'wallet-hunter-f590f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfnqS0vUvGiZ45N8urA1Gh1edLDTB6WOk',
    appId: '1:234336593435:ios:6550a00be953e544087abe',
    messagingSenderId: '234336593435',
    projectId: 'wallet-hunter-f590f',
    storageBucket: 'wallet-hunter-f590f.firebasestorage.app',
    iosBundleId: 'com.example.moodTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfnqS0vUvGiZ45N8urA1Gh1edLDTB6WOk',
    appId: '1:234336593435:ios:6550a00be953e544087abe',
    messagingSenderId: '234336593435',
    projectId: 'wallet-hunter-f590f',
    storageBucket: 'wallet-hunter-f590f.firebasestorage.app',
    iosBundleId: 'com.example.moodTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARbx8YUUIfVtnBwHDL52jc1AHVCqbwq5c',
    appId: '1:234336593435:web:40f6bf79e8bbccf3087abe',
    messagingSenderId: '234336593435',
    projectId: 'wallet-hunter-f590f',
    authDomain: 'wallet-hunter-f590f.firebaseapp.com',
    storageBucket: 'wallet-hunter-f590f.firebasestorage.app',
    measurementId: 'G-12YMWVB9QE',
  );
}
